version: '3.8'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      placement:
        constraints:
          - node.role == worker
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /certs/gitlab.crt:/usr/local/share/ca-certificates/gitlab.crt
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_DESCRIPTION=my-docker-runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=alpine:latest
      - DOCKER_PRIVILEGED=true
      - DOCKER_VOLUMES=/cache
    command:
      - /bin/bash
      - -c
      - |
        update-ca-certificates
        gitlab-runner register --non-interactive --url "$CI_SERVER_URL" --registration-token "$REGISTRATION_TOKEN" --executor "docker" --docker-image alpine:latest --description "my-docker-runner" --tag-list "docker" --run-untagged="true" --locked="false" --access-level="not_protected"

networks:
  gitlab-net:
    driver: overlay

volumes:
  gitlab-runner-config: