version: '3.8'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: gitlab.plank.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.plank.local'
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"    
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitlab-etc:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-opt:/var/opt/gitlab
      - /certs:/etc/gitlab/ssl
    networks:
      - gitlab-net  
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  gitlab-net:
    driver: overlay

volumes:
  gitlab-etc:
  gitlab-log:
  gitlab-opt: