version: '3.8'

services:
  selfsigned-cert:
    image: alpine:latest
    volumes:
      - certs:/etc/ssl/gitlab
    entrypoint: >
      /bin/sh -c "
      apk add --no-cache openssl &&
      mkdir -p /etc/ssl/gitlab &&
      echo '[ req ]' > /etc/ssl/gitlab/openssl.cnf && 
      echo 'distinguished_name = req' >> /etc/ssl/gitlab/openssl.cnf && 
      echo '[ v3_ext ]' >> /etc/ssl/gitlab/openssl.cnf && 
      echo 'subjectAltName = DNS:gitlab.plank.local' >> /etc/ssl/gitlab/openssl.cnf && 
      echo 'basicConstraints = CA:TRUE' >> /etc/ssl/gitlab/openssl.cnf && 
      openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/gitlab/privkey.pem \
      -out /etc/ssl/gitlab/fullchain.pem -days 365 -nodes -subj '/CN=gitlab.plank.local' -extensions v3_ext -config /etc/ssl/gitlab/openssl.cnf &&
      tail -f /dev/null"    
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - gitlab-net

  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.plank.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.plank.local';
        nginx['redirect_http_to_https'] = true;
        nginx['ssl_certificate'] = "/etc/ssl/gitlab/fullchain.pem";
        nginx['ssl_certificate_key'] = "/etc/ssl/gitlab/privkey.pem";
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - certs:/etc/ssl/gitlab:ro
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - gitlab-net

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    environment:
      - CI_SERVER_URL=https://gitlab.plank.local/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
    entrypoint: >
      /bin/bash -c "
      if [ ! -f /etc/gitlab-runner/config.toml ]; then
        gitlab-runner register --non-interactive --url https://gitlab.plank.local/ --registration-token Rglrt-t1_r4hGFKtiKP8pBYhKh1s- --executor docker --docker-image alpine:latest --description 'Docker Runner' --tag-list 'docker' --run-untagged=true --locked=false;
      fi;
      gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - gitlab-net

networks:
  gitlab-net:
    driver: overlay

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:
  certs:
