---
- name: Add Docker GPG key
  ansible.builtin.shell: |
      curl -fsSL {{ docker_gpg_url }} | sudo tee /etc/apt/trusted.gpg.d/docker.asc
  args:
    creates: /etc/apt/trusted.gpg.d/docker.asc

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ docker_ubuntu_repo }} noble stable"
    state: present
    filename: docker

- name: Update repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker
  ansible.builtin.apt:
    name: "{{ docker_install_packages}}"
    state: present

- name: Start and enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ docker_ansible_user }}"
    groups: "{{ docker_group }}"
    append: yes