---
- name: Créer le répertoire Prometheus
  file:
    path: /opt/prometheus
    state: directory

- name: Copier le fichier de configuration prometheus.yml
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Lancer Prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
