---
- name: Upgrade all packages
  ansible.builtin.package:
    name: "*"
    state: latest
    cache_valid_time: 3600

- name: Install common packages
  ansible.builtin.package:
    name: "{{ postinstall_extra_packages_common }}"
    state: present

- name: Create certificate directory
  ansible.builtin.file:
    path: /certs
    state: directory
    owner: "{{ postinstall_user }}"
    group: "{{ postinstall_user }}"
    mode: '0755'
