name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - develop  # ✅ Activation du pipeline sur develop
    paths:
      - 'infrastructure/**/*.tf'
      - 'main.tf'
  pull_request:
    branches:
      - main
      - develop  # ✅ Activation du pipeline sur develop
    paths:
      - 'infrastructure/**/*.tf'
      - 'main.tf'

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 🔍 Debug - Vérification des fichiers clonés
      - name: Debug - Liste des fichiers
        run: ls -R ${{ github.workspace }}

      # 3. Installer Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 4. Configurer AWS Credentials pour Terraform
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      # 5. Initialiser Terraform ✅ Ajout du `working-directory`
      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/

      # 6. Vérifier la validité des fichiers Terraform ✅ Ajout du `working-directory`
      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure/

      # 7. Générer le plan Terraform ✅ Ajout du `working-directory`
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infrastructure/

      # 8. Appliquer les changements Terraform ✅ Ajout du `working-directory`
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infrastructure/
