name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 3. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Validate Terraform files
      - name: Terraform Validate
        run: terraform validate

      # 6. Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 7. Apply Terraform changes (optional)
      # Uncomment this to apply automatically to AWS
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

